name: Deploy Hugo site to Pages

on:
  push:
    branches:
      - master

permissions:
  id-token: write
  pages: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Hugo CLI
        run: |
          wget -O hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.145.0/hugo_extended_0.145.0_linux-amd64.deb \
          && sudo dpkg -i hugo.deb

      - name: Build site with Hugo
        run: env HUGO_ENV="production" hugo --minify --gc --baseURL "https://seungkilee.com/blog/"

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
